name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    # Use the python version installed by Ubuntu 20.04 (version 3.8.5),
    # so we can use precompiled gdal and protobuf
    #- name: Set up Python 3.8
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: 3.8
    - name: Install xmllint and GDAL
      run: sudo apt-get install -y libxml2-utils gdal-bin libgdal-dev python3-gdal
    - name: "Install python dependencies: cram and lxml"
      run: |
        python -m pip install --upgrade pip
        pip install cram lxml
    - name: Testing the code with cram, protobuf not installed
      run: |
        cram test/basic_osm.t
        cram test/basic_pbf_no_protobuf.t
        cram test/charencodings.t
    - name: Install protobuf and osmosis
      run: sudo apt-get install -y libprotobuf-dev protobuf-compiler osmosis
    - name: "Install python dependencies: protobuf"
      run: |
        pip install --upgrade protobuf
    - name: Testing the code with cram, protobuf installed
      run: |
        cram test/basic_pbf.t
